### ISSUE TITLE
Get previous item

### ISSUE THREAD

**Issue by joseronierison** [Dynamoid/Dynamoid#115]
Hi Guys!

I need the previous item id from other item, that is I have id from eleventh item in a list, I need the tenth item id.

Has a way to do that?

Best regards!

**Comment by pboling** [comment]
Can you give a code example of what you are trying to do?  Or the part that you have figured out?

**Comment by richardhsu** [comment]
This is old but I don't think this is possible. At least from documentation, I don't see any viable way to walk backwards in records. You can walk forward if there is a range key specified since objects will be ordered in the scan, but then this would require scanning for elements until the current item is found and you'll have paged in the previous one.

Unless you have the records in memory already which I don't think this is the case.
Can this even be done in general SQL systems? Don't think so unless you know your id's are numeric and can just subtract 1.
