### ISSUE TITLE
Question: How to ensure clean state for testing

### ISSUE THREAD

**Issue by pratik60** [Dynamoid/Dynamoid#217]
Hey!

We started prototyping using Dynamoid, and are really liking the experience compared to aws-record.

One question I have is how can we clean the table after running a test. I have some tests which do check the count of items in a table, and currently have to resort to a delete_table, and create_table in before(:each) block. 

Is there a better way to do this? Can I issue a delete_all in a table?

For reference most companies use https://github.com/DatabaseCleaner/database_cleaner for mysql, postgres, mongoid etc

**Comment by pboling** [comment]
There should be a wiki about testing with Dynamoid, but for now thanks for asking!

Near the top of my `spec/rails_helper.rb`:
```
require 'support/dynamoid'
```

Then later:
```
  config.before(:example, :active_record_clean) do
    DatabaseCleaner[:active_record].strategy = :transaction
  end
  config.before(:example, :mongoid_clean) do
    DatabaseCleaner[:mongoid].strategy = :truncation
  end
  config.before(:example, :redis_clean) do
    DatabaseCleaner[:redis].strategy = :truncation
  end
  config.before(:example, :dynamoid_clean) do
    DynamoidReset.all
  end
```
Note the second argument to the calls to `:before` above.  Those are spec tags, and you use them to mark specific tests as needing a particular type of cleaning.  The nice thing about this setup is your specs end up defining the edges of you data layer dependencies.

I have in `spec/support/dynamoid.rb`:
```
module DynamoidReset
  def self.all
    raise RuntimeError unless Rails.env.test?
    Dynamoid.adapter.list_tables.each do |table|
      # Only delete tables in our namespace
      if table =~ /^#{Dynamoid::Config.namespace}/
        Dynamoid.adapter.delete_table(table)
      end
    end
    Dynamoid.adapter.tables.clear
    # Recreate all tables to avoid unexpected errors
    Dynamoid.included_models.each(&:create_table)
  end
end

# Reduce noise in test output
Dynamoid.logger.level = Logger::FATAL
```

Then a spec might look like:
```
RSpec.describe `A thing` do
  it 'works', :active_record_clean, :mongoid_clean, :redis_clean, :dynamoid_clean do
    expect('all the things').to eq('all the things')
  end
end
```

Those spec tags can go at any level, top describe, middle describe or context, or individual spec definitions.

**Comment by andrykonchin** [comment]
Look at a Test Environment section in the Readme (https://github.com/Dynamoid/Dynamoid#test-environment)

**Comment by pratik60** [comment]
Thanks lads! I can't believe I missed it 🤦‍♂️

**Comment by TheSmartnik** [comment]
@pboling @andrykonchin 

Hi! I am curious why not use `truncate`? Something like

```ruby
created_tables = Dynamoid.adapter.tables

Dynamoid.included_models.each do |model|
  if created_tables.include?(model.table_name)
    Dynamoid.adapter.truncate(model.table_name)
  else
    model.create_table
  end
end
```

Seems logical to use truncate instead of tables recreation

**Comment by andrykonchin** [comment]
Table recreation may be faster in comparison with truncation. DynamoDB doesn't support truncation internally so Dynamoid implements it on its own.

Truncation requires several operations:
- load all the items in a table with Scan
- delete every item with separate Delete call

TBH it could be improved with BatchWriteItem (which could delete 25 items at once) but nevertheless it will still perform at least two operations - loading and deleting (not more then 25 items at once).

Table deletion could be synchronous and not synchronous. In the first case it requires only one call - DeleteTable. In the second case - at least two - to delete a table and to check a table status after some delay. Table deletion is very fast if tests use `dynamodb-local` instead of reaching AWS and DynamoDB . When tests use DynamoDB and actual account table deletion is very slow and table truncation may be much faster.

TBH I didn't compare the speed of truncation and perhaps after improving with BatchWriteItem it could be as fast as table deletion.
