### ISSUE TITLE
Conditional Updates + Updates without find

### ISSUE THREAD

**Issue by pratik60** [Dynamoid/Dynamoid#218]
**Updating item without find**

I'm looking to implement something along the lines of https://docs.aws.amazon.com/sdkforruby/api/Aws/DynamoDB/Client.html#update_item-instance_method

The Active Record way of doing this is `Book.update(id, {author: "Carla"})`. This would ideally issue a request to aws to update the item, and avoids the find. 

I am able to do something like this `Book.find(id).update_attributes({author: "Carla"})`, but this probably does a fetch and then issues the update. 

**Conditional Updates**

If we'd access to the DynamoDb client, I would do something like this for a conditional update. 

```
person = Person.find(id)
new_timestamp = Time.now
self.class.dynamodb_client.update_item(
        table_name: self.class.table_name,
        key: { id: id },
        update_expression: "SET last_contacted_at = :new_timestamp",
        condition_expression: "attribute_not_exists(last_contacted_at) OR last_contacted_at = :original_value",
        expression_attribute_values: {
          ":new_timestamp" => new_timestamp,
          ":original_value" => person.last_contacted_at,
        }
      )
```
Again, I couldn't find an equivalent in the Readme/wiki or issues. The closest being here: https://github.com/Dynamoid/Dynamoid/blob/23362c99e357432210782afb2fa475f1491a7230/spec/dynamoid/persistence_spec.rb#L545-L548

How would you approach this?

**Comment by andrykonchin** [comment]
> The Active Record way of doing this is Book.update(id, {author: "Carla"}). This would ideally issue a request to aws to update the item, and avoids the find.

Actually ActiveRecord loads record, sets new attributes values, validates, runs callbacks and saves. It makes sense to have this hight level functionality here in Dynamoid. I am not sure it makes sense to have low level operation what you propose on the Document level.

> If we'd access to the DynamoDb client, I would do something like this for a conditional update

If you need just to access DynamoDB client connected to the server just use `Dynamoid.adapter.client`.

There is a tiny wrapper class what makes things a little simpler `Dynamoid.adapter` and you can make conditional upsert like you want with `Dynamoid.adapter.update_item` (https://github.com/Dynamoid/Dynamoid/blob/master/lib/dynamoid/adapter_plugin/aws_sdk_v2.rb#L385).

**Comment by andrykonchin** [comment]
@pboling 

There is `#upsert` method in `Mongoid` (https://docs.mongodb.com/mongoid/master/tutorials/mongoid-persistence/).

They use it in following way:

```ruby
person = Person.new(
  first_name: "Heinrich",
  last_name: "Heine"
)
person.upsert
```
This only runs the `{before|after|around}_upsert` callbacks.

---

Extension of Rails ActiveRecord (https://github.com/jesjos/active_record_upsert) propose following interface:

1) class method `.upsert`
 `MyRecord.upsert(id: 1, wisdom: 3)`
2) Similar to `Mongoid` `#upsert` method
```ruby
r = MyRecord.new(id: 1)
r.name = 'bar'
r.upsert
```
3) Both `.upsert` and `#upsert` accept conditions
`MyRecord.upsert({id: 1, wisdom: 3}, arel_condition: ...)`

---

So what do you think if we add something like this to the `Dynamoid::Document`?

**Comment by pboling** [comment]
I think that would be an excellent addition!  Let's add `record.upsert`.  I also thing there is value in an update with raw ID without loading the record first.  This would be like in ActiveRecord doing:
```
# No admins named Bob are allowed
User.where(name: "Bob").update_all({admin: false})
```

https://apidock.com/rails/ActiveRecord/Relation/update_all

**Comment by andrykonchin** [comment]
@pboling @richardhsu
Actually I am confused now. I cannot chose a name for asked "updating" operation.

It isn't `upsert` because we don't want to create a new item. We shouldn't use `update` name because as I wrote above it's implemented in ActiveRecord and it loads record, validates and saves (so we have two queries instead of one) but here we need to make only one low-level update without callbacks and validation.

I can imagine only following interface:

`Document.update({})` behaves like it does in ActiveRecord
but `Document.update({}, validate: false, run_callbacks: false)` will use low-level `UpdateItem` and just update attributes.

What could you suggest?

**Comment by pboling** [comment]
```
Document.update(id, {author: "Carla"})
```
When used as a class method, with the intent being to not load the object first, we can't run callbacks, and I don't think validations can be consistent either.
If called this way it should only commit the changes.

**Comment by andrykonchin** [comment]
@pboling 

My concern is it may confuse user. ActiveRecord's `update` method has different semantic as I wrote earlier (https://apidock.com/rails/ActiveRecord/Base/update/class) and it may be useful to have shortcut for `Document.find().update()` to validate model and run callbacks as well. 

It isn't clear looking at the name what semantic the method `.update` has.

For instance there are `Model#update_attribute` in Mongoid (https://docs.mongodb.com/mongoid/master/tutorials/mongoid-persistence/) and `Model#update_columns` in ActiveRecord (https://apidock.com/rails/ActiveRecord/Persistence/update_columns) to update attributes directly and bypass both callbacks and validations.

So we can introduce `.update` method to run validations and callbacks and something like `.update_fields` to bypass them and to make low-level `UpdateItem` request (and `#upsert`/`.upsert` methods as well but looks like it's another story).

The issue is to choose proper and meaningful names.

What do you think?

**Comment by pboling** [comment]
This is the current version of `update` for Rails 4/5:
https://apidock.com/rails/ActiveRecord/Relation/update

I believe we can use that exact semantic in Dynamoid, such that:

```
Document.update(id, {author: "Carla"})
```

Does the same thing in ActiveRecord as it does in Dynamoid.  Once we have that, which I think is the main concern of this issue, I think we can discuss the other APIs.

**Comment by richardhsu** [comment]
I think the semantic of `update` on the class as @pboling suggests is good but if we were to stick with being in parity with Rails this would need to be implemented with validations as the apidock mentions which means it's going to do 2 queries.

------------------

Focusing on @pratik60's original concern I think in ActiveRecord land the only way to do an update with low-level SQL call without the actual record on hand would be to do something like:

```
Document.where(id: 5).update_all(author: "Carla")
```

This will then do:

```
UPDATE "documents" SET "author" = 'Carla' WHERE "documents"."id" = 5;
```

So if we have this managed in Dynamoid as well (not sure if we do since I don't see any reference of `update_all` in our codebase) then it'd match to the conditional updates without doing 2 queries.

And we'd support the proper querying though I don't know if it'd properly support the same semantics for conditional updates.

--------------------

On the note about `update_fields`:

```
Document.find(5).update(author: "Carla")
Document.find(5).update_columns(author: "Carla")
Document.where(id: 5).update(author: "Carla")
Document.where(id: 5).update_columns(author: "Carla")
```

I believe all 4 of these actually issue 2 queries: (1) for `SELECT` and (2) for `UPDATE`.

But I think if we short-circuit and allow our `update_fields` as @andrykonchin suggests to avoid the lookup since it doesn't do any validation or callbacks, that sounds good to me and seems as a developer what I'd expect, the low-level call similar to `update_columns` because really if I'm skipping validations and callbacks, there's no need to even do the initial lookup because I'm already coding it in a best-effort optimistic way.

**Comment by pboling** [comment]
Ah yes, to bypass validations w*and* match Rails' syntax we would need to do:
```
Document.where(id: 5).update_all(author: "Carla")
```

**Comment by andrykonchin** [comment]
@pboling @richardhsu 

OK.
If there is no any objection I will work on `update`/`upsert`/`update_fields` implementations.
