### ISSUE TITLE
Signifying a Composite Key

### ISSUE THREAD

**Issue by Rheisen** [Dynamoid/Dynamoid#265]
I'm creating a model class for a Dynamo table and there doesn't appear to be any documentation on providing a composite key for the key value and I'm not sure what the appropriate way to do this is.

E.g.

class MediaItem
  include Dynamoid::Document
  table :name => MediaItem, :key => ?

end

where the key would be :media_pack_id and :user_id for example.

**Comment by andrykonchin** [comment]
Yeah, the documentation still isn't comprehensive and DSL uses old terminology (hash/range key instead of partition/sort key) and it may confuse.

You example could be rewritten in following way:

```ruby
class MediaItem
  include Dynamoid::Document

  table :name => :media_items, :key => :media_pack_id
  range :user_id
end
```

You can find some examples in specs (https://github.com/Dynamoid/Dynamoid/blob/master/spec/app/models/message.rb)

**Comment by andrykonchin** [comment]
Looks like the value of either hash key or range key doesn't match type of values you already have in the table. Dynamoid uses UUID as a primary key, default name - `id`, type - `:string`.

Please ensure your schema matches the actual values you try to save

**Comment by Rheisen** [comment]
It appears I was trying to run queries against it without giving it enough information - things seem to be working now, sorry for the trouble!
