### ISSUE TITLE
created_at and updated_at not being set.

### ISSUE THREAD

**Issue by varchar** [Dynamoid/dynamoid#284]
The dynamoid config has timestamps: true, the console shows the fields as present (#<ProductStyleScore:0x00007fabaacef3f8 @attributes={:created_at=>nil, :updated_at=>nil), but the aws console doesn't show the fields as being present.  Shouldn't dynamoid be auto-populating these fields?

```class ProductStyleScore
  include Dynamoid::Document

  table key: :customer_id
  range :product_id

  field :customer_id, :integer
  field :product_id, :integer
  field :score, :integer
  field :reasons, :array, of: :string
  field :scorer, :string

  validates_presence_of :customer_id, :product_id, :score
end```

and all records comeback with nil set for created_at and updated_at

**Comment by andrykonchin** [comment]
Right, Dynamoid should set these fields if Dynamoid::Config.timestamps is true.

What Dynamoid version do you use?
Could you please provide a minimal example to reproduce the issue?

**Comment by varchar** [comment]
`ProductStyleScore.upsert(customer.id, product.id,
                            { score: score, reasons: reasons, scorer: Commands::ProductScorer.version })`

using dynamoid 2.2

**Comment by andrykonchin** [comment]
I see. It's a not intentional limitation of `update_fields` and `upsert` methods. At least it worth to document it.

It's reasonable to change `updated_at` in the `update_fields` method. Good catch 👍 .

But I am not sure it will be possible to set/update timestamps in `upsert` correctly:
- it's OK to set `created_at` and `updated_at` if document doesn't exist and we create new one
- it isn't OK to update `created_at` and `updated_at` when document exists.

The main value of `upsert` is to make changes effectively. The only option is `UpdateItem` API call. It creates new document with specified attributes or updates existed. We can set `created_at` when document doesn't exist and skip it when a document exists with only one API call.

(https://docs.aws.amazon.com/amazondynamodb/latest/APIReference/API_UpdateItem.html)

So we need to
* update README and state `upsert` doesn't set timestamps
* and set `updated_at` in `update_fields` method

Does it make sense?

**Comment by pboling** [comment]
That makes sense to me. 👍

**Comment by varchar** [comment]
Could you automatically set the updated_at?  That field would be fine to overwrite on each upsert.

**Comment by andrykonchin** [comment]
Yep. It makes sense.

**Comment by andrykonchin** [comment]
Done
