### ISSUE TITLE
What if an existing DB has a field with a name that's reserved by dynamoid (e.g. "type")

### ISSUE THREAD

**Issue by launchbyte-dev** [Dynamoid/dynamoid#297]
We're working with a DB that has a table with a field named "type".  

When we try to access data from that table with values in the "type" field (e.g. type="XXX"), we get an error: "NameError: Uninitialized constant XXX.

When we try to access data from that table without values in the "type" field, it returns the record correctly, but, with the table name as the value for the type field.

Is there a way to tell dynamoid to treat a field named "type" specially in some way?  Maybe give it an alias under the covers or something?

Thanks!

**Comment by pboling** [comment]
Here is the list of reserved words in DynamoDB:
https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/ReservedWords.html

Please do not use those words to name tables, attributes or other objects.

From the documentation:
> Although DynamoDB allows you to use these reserved words and special characters for names, we recommend that you avoid it because you have to define placeholder variables whenever you use these names in an expression.

So while it is possible to support reserved words as object names, we have no plans to support it.  If you would like to see support you might need to fork the repo, and open a pull request adding that support.

**Comment by andrykonchin** [comment]
The issue is that Dynamoid uses `type` field to support `STI` like it's done on Rails ActiveRecord. So `type` value is treated as a class name of some class hierarchy. 

There is a way to handle this issue In Rails by specifying another column name for STI with [inheritance_column](https://apidock.com/rails/ActiveRecord/Base/inheritance_column/class) in the model.

Looks like it's a good feature to implement in Dynamoid.

@pboling @richardhsu Does it make sense?

**Comment by pboling** [comment]
I would be happy to see it implemented @andrykonchin  - I just don't have time to do it myself. 👍

**Comment by andrykonchin** [comment]
@pboling Great. Will work on it right after releasing 3.0 version.

**Comment by andrykonchin** [comment]
Fixed
