### ISSUE TITLE
Why did you rename limit method to eval_limit?

### ISSUE THREAD

**Issue by hnishide** [Dynamoid/Dynamoid#30]
Is there any collision?

**Comment by philipmw** [comment]
Hello. I renamed `limit` to `eval_limit` because `limit` was misleading. In ActiveRecord, `limit` controls how many items matching your predicate _you get back_, whereas with DynamoDB it controlled how many items were _evaluated_ for your predicate.

With DynamoDB, you could run your query on a large table, limit it to 10 items, and get 0 items back because the first 10 items in the table happened to not match your predicates.

So to avoid this confusion and inconsistency between AR and DynamoDB, I renamed `limit` to `eval_limit`, to emphasize that you're limiting the number of evaluations rather than resulting rows.

**Comment by hnishide** [comment]
Thanks a lot!
I completely understand and agree with you.
