### ISSUE TITLE
Question about `where` and `find`

### ISSUE THREAD

**Issue by rhuang** [Dynamoid/dynamoid#315]
1. For `where`, is it a naive scan if the field isn't part of a GSI?
In the example in the documentation, `Address.where(city: 'Chicago')`, if `city` isn't the hash key of a GSI, then would it be a scan? And if `city` is the hash key of the GSI, then `where` would do a query?
I'm trying to figure out if I should use `where` or the explicit `find_all_by_secondary_index` to use the GSIs that I define.

2. If I define a hash key and a range key for the table, a composite key, how do I `find` it? From what I can read from the documentation, `find` seems to only work only if the table only has a hash key as the primary key.

3. If I define a GSI with the hash key and the range key, can I query on the GSI using `find_all_by_secondary_index` without specifying the range key? For example I just want to query using the hash key on the GSI without sorting/filtering with the range key. I can't seem to do that with `find_all_by_secondary_index`.

**Comment by andrykonchin** [comment]
1. If `where` 's conditions contain GSI hash key - it will be query, otherwise - scan. There are some limitations. The GSI should be declared in a model class with `global_secondary_index` and `projected_attributes` options should be `:all`. Another one - if there are several GSI with the same hash key first one will be chosen.
You can log HTTP requests and responses with `debug` logging level to make sure the right request to DynamoDb is made:
```ruby
Dynamoid::Config.logger.level = :debug
```

2. `find` works well with composite keys. Look at examples in the documentation [here](https://www.rubydoc.info/github/Dynamoid/dynamoid/master/Dynamoid/Finders/ClassMethods#find-instance_method):

```ruby
Document.find(101, range_key: 'archived')
```

3. Looks like it doesn't work now. `find_all_by_secondary_index` is deprecated and could be completely replaced with `where`. Please let us know if option with `where` does't work for you.

**Comment by rhuang** [comment]
Thanks! One more question:
For `where`, if I have a GSI with hash and range key, for example on `qid` (hash) and `client_id` (range), then this would query the GSI appropriately?

For example: `Document.where(qid: 'qid', client_id: 'client_id')`

I'll turn on debug logging and check the requests too. Thanks for the help.

Regarding (3), I was testing quickly and found that `find_all_by_secondary_index` seems to work for GSI with both hash and range key if I make 2 definitions of the GSI:

`global_secondary_index hash_key: :age, range_key: :height`
`global_secondary_index hash_key: :age`

Then I can query using `find_all_by_secondary_index` with a `nil` range key or a range key that's not `nil`.

But I will migrate to use `where`.

**Comment by andrykonchin** [comment]
> For where, if I have a GSI with hash and range key, for example on qid (hash) and client_id (range), then this would query the GSI appropriately?

Yes. It will use GSI.

**Comment by rhuang** [comment]
Thanks Andrew. Closing now.
