### ISSUE TITLE
Non Skip-Take Pagination

### ISSUE THREAD

**Issue by arjes** [Dynamoid/dynamoid#338]
Hello,

DynamoDB Pagination is a bit different then the skip take (LIMIT & OFFSET driven) pagination we are most developers are used to. Dynamoid offers wrappers to make DynamoDB pagination look like this, but it isn't the native pagination for DynamoDB.

For my use case it is desirable to use the default DynamoDB pagination style, but this isn't exposed anywhere in Dynamoid that I could find. I can add the feature and submit a PR, but I would like to start a discussion on how this should be exposed to the consumers of the library.

So here are my first two ideas:

```ruby
# Given some query...
query = Model.where(foo: 'bar').start(params[:restart_key])

# Return a tuple
records, restart_key = query.next_page

# Return a Hash
data = query.next_page # => {records: [...], restart_key: 'foobar'}
```

**Comment by pboling** [comment]
I really like this idea!

**Comment by richardhsu** [comment]
What would be the difference of this and the limit features? See https://github.com/Dynamoid/dynamoid#limits

The way you'd use it similar to README and should work similar to the following:
```
records = Model.where(foo: 'bar').record_limit(5)
next_5_records = Model.where(foo: 'bar').record_limit(5).start(records.last)

# Or to get them all with your own pagination
bookmark = nil
loop do
  records = Model.where(foo: 'bar').record_limit(5).start(bookmark)
  bookmark = records.last
  process_records(records)
end
```

I believe `start` given a `nil` input will just ignore it.

**Comment by andrykonchin** [comment]
@arjes Could you please clarify what problem you do encounter and would like to solve with your proposal?

The gem isn't documented well so there may be already suitable solution.

**Comment by arjes** [comment]
@andrykonchin In the end I am looking to only retrieve one page s DynamoDB defines it at a time. I've been in and out of the code quite a bit but mostly in V2. We are using DynamoDb fairly heavily at work and have a few [extensions for dynamoid](https://github.com/GetTerminus/dynamoid-advanced-where)

In the end I am trying to solve a problem of efficiency, DynamoDB defines pages essentially by [data size](https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/Query.html).

> DynamoDB paginates the results from Query operations. With pagination, the Query results are divided into "pages" of data that are 1 MB in size (or less). An application can process the first page of results, then the second page, and so on.

This means that the first page of results could be 2 items, if they are both near the maximum document size, or could easily range into the hundreds as the documents shrink in size. By approaching the problem with a skip take mindset (which has its own issues in RDMSs) we ingrain that inefficiency. DynamoDB is inherently different then PG, MySQL etc, and we should encourage people to think differently too! (But of course give them what they are used to)

I can go into detail if you all would like, but my general position would be:

1) The number of records to show on screen is a concern of the frontend, not the backend. 
2) Design constraints dictate the API's behavior
3) More often than not, APIs end up constrained by response time. Making a variable number requests makes it far harder to control p95.
4) Multiple ajax requests allow a frontend framework to begin rendering sooner

The `.record_limit(x).start(y)` approach ingrains inefficiency, if we have small record we could very well get pages 1-10 out to the frontend with one Dynamo call, instead of 10 for the same set.

As it stands right now, the `start` method takes a hash as input, but  I don't see a way to get a hash. Given your standard paginated use case, how you envision people asking the question, 10 records starting on page 7? From what I can see this would requiring sending the record ID back to the client and reloading the record for page 2?

So this may have been a bit rambling, but here are the features I'm looking to add:

1) The ability to get 1 page as defined by the datastore.
2) Any efficient way to serialize the "next page" data into a token to send to the client

**Comment by richardhsu** [comment]
Right now the scan/queries will stop making backend calls based on the `record_limit` or `scan_limit`, otherwise it will attempt to fulfill the query with as much as it can by paginating internally and returning the full set on call. So like you said this has it's inefficiencies.

I can then see adding an extra flag to basically be `call_limit` which basically is the number of underlying DynamoDB calls allowed to make to fulfill the query. 

As a side note, `start` should be able to take both a hash and a record, that record however must contain all the necessary hash/range keys in order to index for the query. If that doesn't work, that's a bug as I expanded it to hopefully utilize both a record or a hash.

I do understand though of wanting to be efficient and for front-ends having better guarantees on return time for each page which in DynamoDB case would be based best on the data call return since your network round trip could be what is considered expensive.

However, in this case how I'd envision it working since you cannot guess how your offsets would be done for any given page N, it'd be:

```
records = Model.where(foo: 'bar').call_limit(1)
# This will then return N records based on the maximum allowed by DynamoDB data size constraint in a response

next_records = Model.where(foo: 'bar').call_limit(1).start(records.last)
# This again will return M records based on the maximum allowed by DynamoDB data size constraint in a response starting at the last record you've seen
```

----------

**How would give me page 10 work?**

Assuming you haven't realized any of the records yet, naively:
```
bookmark = nil
2.times do
  records = Model.where(foo: 'bar').call_limit(10).start(bookmark)
  bookmark = records.last
end
# records should now store page 10's data
```

For efficiency one could cache the `records.last` in order to query for already seen pages more efficiently; however, note any additions or deletions to the table, technically breaks the pagination somewhat since pages can then shift depending on where new records are added or records are deleted (this is true in any case).

Serializing this bookmark, I'd suggest since you actually know better about the query, you can easily determine what the `start` hash should be given a record, since it's based on the `hash_key` and the `range_key` depending on if you're using the primary global index or a secondary global index to query. So for example if you are just on the primary index then you can have the `start` be `{ id: records.last.id }`

You can see `dynamoid/chain.rb` for `start_key` method which attempts to construct the proper hash key based on the given record input (`@start`) based on what it knows of the document.

```
      # Start key needs to be set up based on the index utilized
      # If using a secondary index then we must include the index's composite key
      # as well as the tables composite key.
      def start_key
        return @start if @start.is_a?(Hash)
        hash_key = @hash_key || source.hash_key
        range_key = @range_key || source.range_key

        key = {}
        key[hash_key] = type_cast_condition_parameter(hash_key, @start.send(hash_key))
        if range_key
          key[range_key] = type_cast_condition_parameter(range_key, @start.send(range_key))
        end
        # Add table composite keys if they differ from secondary index used composite key
        if hash_key != source.hash_key
          key[source.hash_key] = type_cast_condition_parameter(source.hash_key, @start.hash_key)
        end
        if source.range_key && range_key != source.range_key
          key[source.range_key] = type_cast_condition_parameter(source.range_key, @start.range_value)
        end
        key
      end
```

Thoughts and concerns?

**Comment by bmalinconico** [comment]
I saw that `start` took a hash, but I was unable to find _how_ I could obtain that hash from a record.

So I would 1,000% advocate against "getting page 10" through iteration. _If_ Dynamoid wanted to support that I would  advocate doing it in library and skipping the hydration of a lot of intermediate objects. I would be happy to talk through this more but it is tangental to the pagination I am implementing.

DynamoDB lends itself to token based pagination, and that is how we are approaching it. The server is responsible for returning the client a token which the client can use to get the next page. At the most trivial level this would be a Base64 encoding of the LastEvaluatedKey as json, however at a more practical level it could also include serialized search parameters. Using token based pagination there is no skipping to page X, and in many cases there are may not even be a total Number of records. DynamoDB also makes it a pain to tell when you are at the last record.

Here is the flow we are working through for a UI that wants 10 items(made up):
```
GET /report?start_date=2019-01-01&end_date=2019-02-01
=> { records: [1,2,3], metadata: {next_page_token: 'foobar' }}
GET /reports?page_token=foobar
=> { records: [4,5], metadata: {next_page_token: 'foobar2' }}
GET /reports?page_token=foobar2
=> { records: [6,7,8,9,10,11,12,13,14], metadata: {next_page_token: 'foobar3' }}
```

When the user moves on to page2, we already have record 11-14, but will make the next request to continue the search. 

We are generally taking the approach that, if users are trying to get to page X of a search, there is a missing filter.

## Call Limit
The use of call_limit may work. Would also need to expose a method to let clients generate the start key from the last record.


```
class SomeController
  def report
     query = SomeModel.where(whatever: 'foo')
     results = query.call_limit(1).all
    render json: {
      records: results, 
      metadata: {
        restart_token: query.to_restart_key(results.last) # Practically this should probably be encoded
      }
    }
  end
end
```

**Comment by richardhsu** [comment]
@bmalinconico, I agree, I'm sorry I wasn't suggesting we actually do that, just naively explaining how you cannot determine page 10 without realizing some iteration of data because there is no "fixed" way to offset into the queries.

@bmalinconico yes it takes a hash but it should also take a record, see the implementation I copied from the code, it handles it as a hash directly OR it'll try to determine the hash based on a record given. Thus you don't need to determine the hash yourself, it should calculate it automatically. Based on that code, generating the hash is based on the hash key and range key of whatever index you are using. Again you shouldn't need to worry about creating the hash, the method `start` will handle that for you given a record object. 

However, yes I agree we can expose a method to be able to given a record create the hash since when you get callback from front-end you may not have the record object anymore. Base64 encoding seems sufficient enough, since it's a hash of data.

What do you mean on the practical level though with search parameters?
I think I would see the requests be more as follows:

```
GET /report?start_date=2019-01-01&end_date=2019-02-01
=> { records: [1,2,3], metadata: {next_page_token: 'foobar' }}
GET /reports?start_date=2019-01-01&end_date=2019-02-01&page_token=foobar
=> { records: [4,5], metadata: {next_page_token: 'foobar2' }}
GET /reports?start_date=2019-01-01&end_date=2019-02-01&page_token=foobar2
=> { records: [6,7,8,9,10,11,12,13,14], metadata: {next_page_token: 'foobar3' }}
```

As this is what most paginated systems with filters would do, send the same query parameters and then send `page=1` for ones that do handle offsets. But please clarify if I'm misunderstanding what you mean by "serialized search parameters".

Below just quick run down of manually creating the hashes:

## Generating Hash Overview

Example for Primary Index uses just the hash key which for most is `id`
```
{ id: 1 }
```

If you have a record just make sure to construct the hash based on the record's ID.

Example for Primary Index with hash key `id` and with range key say `updated_at` then it'd be:
```
{ id: 1, updated_at: '2019-01-01' }
```
Or whatever your `updated_at` time format is.

However, this is completely dependent on your index.

For example if I have a Users document that has these fields:

* ID
* Created At
* Country
* Age


**Indices:**

1. Primary index based on `id` with no range key
2. Secondary index based on `country` with range key `age`
3. Secondary index based on `country` with range key `created_at`

The `start_key` method will attempt to construct which hash it needs based on the criteria given and do best effort but to be exact example of hashes should be:

1. Primary index based on `id` with no range key
  * `{ id: 3}`
2. Secondary index based on `country` with range key `age`
  * `{ country: 'USA', age: 3 }`
3. Secondary index based on `country` with range key `created_at`
  * `{ country: 'USA', created_at: 3 }`

As these are based on the way the query would be done for Dynamo.

**Comment by andrykonchin** [comment]
@arjes 

Okay, I understand your objectives so it definitely makes sense to give some control over DynamoDB's pagination and api requests. Despite it makes abstractions leak in favor of efficiency.

There were mentioned several options how to extend Dynamoid - `#next_page` and `#call_limit`. Personally I prefer more Rubyish interface of enumerators, lets call it `#pages`, that will return lazy collection of pages. Page - means an array of instantiated models.

So getting first page would look like this:

```ruby
Model.where(foo: 'bar').start(bookmark).pages.first
```

It's a general interface to all the methods of `Enumerable` would be available like `map` and `#take`.

If it's what solves your problem and there are no arguments against naming I would approve this change. The implementation is really simple and cheap so I could do it this week.

**Comment by arjes** [comment]
@richardhsu 

> As this is what most paginated systems with filters would do, send the same query parameters and then send page=1 for ones that do handle offsets. But please clarify if I'm misunderstanding what you mean by "serialized search parameters".

This is 100% an internal choice, not related to Dynamoid sorry for the tangent. 

Thanks for the rundown on the restart hash. Since it is dependent on the index being scanned, the hash would need to be generated by the Chain, which may make the restart key of `Model.all` a bit more awkward.

@andrykonchin I too prefer my lazy enumerable, and the stream of records will be fine as long as we expose some method of generating restart hashes.

 Maybe `find_by_pages` to be more analogous to AR's `find_in_batches`.  

If you feel like taking it on, awesome, but I can certainly lend a hand.

**Comment by andrykonchin** [comment]
@arjes 

Yeah, `find_in_batches` is a good example.

> If you feel like taking it on, awesome, but I can certainly lend a hand.

Okay, it would be great to have a PR with this feature. So go ahead!

The only thing confuses me a bit is similarity of `find_by_pages` name with dynamic finders `find_by_<smth>`. May it confuse users as well?

**Comment by andrykonchin** [comment]
> as long as we expose some method of generating restart hashes

As @richardhsu mentioned several times the "restart hash" depends on DynamoDB's index used in case of performing `Query` operation. But there is no any index identifier on the Dynamoid level of logic (TBH it is present but is internal only). 

In general case user will have to specify the index "id" as argument.

So we can do following:
* add index name/id option to index declaration (I mean declaration of global/local secondary index)
* add method to provide hash with hash_key/range_key ("restart" hash). It may return keys for primary index by default and for specified as argument index name/id

@richardhsu What do say about this idea?

**Comment by bmalinconico** [comment]
I understand that they are dependent on the index in use, and therefore the constructed query. My suggestion a few comments back was to expose this as part of chain.

```
query = Model.where(foo: 'bar')
records = query.find_in_pages.first

return { records: records, restart_key: query.some_restart_key_build(records.last) }
```

This will allow the method to work with Dynamoid's implicit GSI detection no?

**Comment by andrykonchin** [comment]
@bmalinconico Sounds good.

**Comment by arjes** [comment]
To follow up. The PR is in-place exposing the pages, and I'm finalizing my reading into the restart key generation.

I'll continue along that path we discussed earlier, using a record to generate the key. However I can't find anywhere in the DyanamoDB docs that indicate how to manually construct a ExclusiveStartKey.

This makes me nervous, since the docs are really pushing you towards the "Use what we give you" direction. If we are manually generating these hashes with non-documented behavior we do risk them changing without warning. Of course that is unlikely, but still.

**Comment by andrykonchin** [comment]
It's true. I haven't found any documented way to get `ExclusiveStartKey ` except using `LastEvaluatedKey` either.

Looks like it's time to make abstraction leak and to return api response details like `LastEvaluatedKey` to the `Chain` class level from the adapter's one.

**Comment by arjes** [comment]
Alright, so let's talk options. I only started refactoring common code so I'm not too far into it.

First pass, which works naturally when working with pages:

```ruby
# Backwards compatible, with any yielder. Only taking one argument will drop the second
model.find_pages do |items, metadata| 
  # Metadata contains all non-items in the response
end
```

```
{
   "ConsumedCapacity": { 
      "CapacityUnits": number,
      "GlobalSecondaryIndexes": { 
         "string" : { 
            "CapacityUnits": number,
            "ReadCapacityUnits": number,
            "WriteCapacityUnits": number
         }
      },
      "LocalSecondaryIndexes": { 
         "string" : { 
            "CapacityUnits": number,
            "ReadCapacityUnits": number,
            "WriteCapacityUnits": number
         }
      },
      "ReadCapacityUnits": number,
      "Table": { 
         "CapacityUnits": number,
         "ReadCapacityUnits": number,
         "WriteCapacityUnits": number
      },
      "TableName": "string",
      "WriteCapacityUnits": number
   },
   "Count": number,
   "LastEvaluatedKey": { 
      "string" : { 
         "B": blob,
         "BOOL": boolean,
         "BS": [ blob ],
         "L": [ 
            "AttributeValue"
         ],
         "M": { 
            "string" : "AttributeValue"
         },
         "N": "string",
         "NS": [ "string" ],
         "NULL": boolean,
         "S": "string",
         "SS": [ "string" ]
      }
   },
   "ScannedCount": number
}
```

This just simply doesn't make sense unless you work in pages, since your standard limit stops mid page.

Do we want to expose this only for paged based iteration and maintain current `start` behavior for other iteration patterns?

**Comment by andrykonchin** [comment]
> Do we want to expose this only for paged based iteration and maintain current start behavior for other iteration patterns?

Yes, it makes sense only for paging with (with `find_in_pages`) and I would expose only `LastEvaluatedKey` as a `metadata` parameter at least for now

**Comment by bmalinconico** [comment]
I think this request is now complete. What is your release frequency? I'm going to point my code at master for now.

**Comment by andrykonchin** [comment]
Usually we release every 3-4 months but the last one is postponed a little longer. I am going to release recent changes in a month or so.

**Comment by andrykonchin** [comment]
The feature was release in 3.2.0. I will close the issue until some issue occurs.
