### ISSUE TITLE
Update bin/setup to use docker.io?

### ISSUE THREAD

**Issue by postmodern** [Dynamoid/dynamoid#345]
Instead of directly downloading dynamodb-local, perhaps `bin/setup` could install dynamodb-local from [docker hub](https://hub.docker.com/r/amazon/dynamodb-local/)?

**Comment by andrykonchin** [comment]
There are several ways to setup local environment using
- `bin/setup` (MacOS specific script)
- Vargrant
- Docker Compose

Not sure whether it's reasonable to update `bin/setup` but it's definitely makes sense to use official docker image in `docker-compose.yml` instead of some unofficial.

https://github.com/Dynamoid/dynamoid/blob/master/docker-compose.yml#L5

**Comment by postmodern** [comment]
Created pull #347.
