### ISSUE TITLE
ArgumentError: Unknown validator: 'UniquenessValidator'

### ISSUE THREAD

**Issue by steveburkett** [Dynamoid/dynamoid#349]
hi there, 

I get an error trying to add a uniqueness validator to my dynamoid model.  The docs say we can use activerecord validations right?  

In this case, i want the the validation to fail if book_version_id is NOT unique IF finished_time is nil.  

[ruby-2.5.0](git:sb/schedule_indexing_jobs):open-search $  be  rake dynamoid:create_tables
rake aborted!
ArgumentError: Unknown validator: 'UniquenessValidator'

```
class IndexingJob
  include Dynamoid::Document

  VALID_STATES = %w(PENDING STARTED FINISHED)

  validates_inclusion_of :state, :in => VALID_STATES
  validates :book_version_id, uniqueness: { scope: :finished_time,
                                 message: "must be unique if not finished" }
```

**Comment by andrykonchin** [comment]
Yeah, `Dynamoid` reuses `Rails`' validations (`ActiveModel` validators TBH) but doesn't support some of them related to `ActiveRecord` like `uniqueness` validation.

Uniqueness check means performing full scan through the table so it's very expensive operation. That's why it's very unlikely you would use it.

As a workaround you can do this check manually or implement and register validator on your own with `validates_with` method [(Rails Custom Validators)](https://guides.rubyonrails.org/active_record_validations.html#performing-custom-validations)
