### ISSUE TITLE
Klass.count returns 0 but Klass.where({}).count returns correct count

### ISSUE THREAD

**Issue by prcongithub** [Dynamoid/dynamoid#430]
This happens only when connected to DynamoDB on AWS.

We don't face this issue with local DynamoDB running in a docker container.

Dynamoid Version: 3.5.0
DynamoDB Local: Latest amazon/dynamodb-local image
DynamoDB AWS

```
irb(main):005:0> PushNotification.count
=> 0
irb(main):006:0> PushNotification.where({}).count
=> 1004
irb(main):007:0> PushNotification.create!(title: "Test 1")
=> #<PushNotification:0x2133b712 @_touch_record=nil, @changed_attributes={}, @associations={}, @previously_changed={"title"=>[nil, "Test 1"], "created_at"=>[nil, Thu, 23 Apr 2020 15:02:42 +0000], "updated_at"=>[nil, Thu, 23 Apr 2020 15:02:42 +0000], "id"=>[nil, "e7c406b5-0ddb-4e7d-9682-10e7ead1270d"]}, @attributes={:title=>"Test 1", :created_at=>Thu, 23 Apr 2020 15:02:42 +0000, :updated_at=>Thu, 23 Apr 2020 15:02:42 +0000, :id=>"e7c406b5-0ddb-4e7d-9682-10e7ead1270d"}, @new_record=false, @validation_context=nil, @attributes_before_type_cast={:title=>"Test 1", :created_at=>Thu, 23 Apr 2020 15:02:42 UTC +00:00, :updated_at=>Thu, 23 Apr 2020 15:02:42 UTC +00:00, :id=>"e7c406b5-0ddb-4e7d-9682-10e7ead1270d"}, @errors=#<ActiveModel::Errors:0x5ca4c88a @messages={}, @base=#<PushNotification:0x2133b712 ...>, @details={}>>
irb(main):008:0> PushNotification.where({}).count
=> 1005
irb(main):009:0> PushNotification.count
=> 0
irb(main):010:0> 
```

```
class PushNotification
  include Dynamoid::Document
  
  table name: :push_notifications

  # fields declaration
  field :title, :string
  
  field :body, :string
  
  field :payload
end
```

**Comment by andrykonchin** [comment]
Thank you for the question.

Actually it's an expected behavior, but looks like not documented properly.

`Model.count` method returns an approximated value based on AWS DynamoDB internal statistic. Internally Dynamoid makes [DescribeTable](https://docs.aws.amazon.com/amazondynamodb/latest/APIReference/API_DescribeTable.html) API call and returns [ItemCount](https://docs.aws.amazon.com/amazondynamodb/latest/APIReference/API_TableDescription.html#DDB-Type-TableDescription-ItemCount) value.

`Model.where(...).count` is implemented in different way. It returns accurate value actually "reading" all the items using either `Query` or `Scan` operations. Internally it doesn't load all the items from the DynamoDB but only size of items which satisfy the filtering conditions. It's done with [Select option](https://docs.aws.amazon.com/amazondynamodb/latest/APIReference/API_Query.html#DDB-Query-request-Select) with value `COUNT`.

So these methods differ in both accuracy and cost. `DescribeTable` call is almost free but `Query`/`Scan` can be very expensive in terms of throughput and money.

Hope I answered your question.  The documentation will be updated to prevent such confusing.

**Comment by prcongithub** [comment]
Thank for the quick revert @andrykonchin .

So this is not an issue with locally runnning dynamodb. This happens only when we connect to DynamoDB tables on aws cloud. 

Is that also expected?

**Comment by andrykonchin** [comment]
It seems to me this is expected. According to the [documentation](https://docs.aws.amazon.com/amazondynamodb/latest/APIReference/API_TableDescription.html#DDB-Type-TableDescription-ItemCount) for `ItemCount`:

> DynamoDB updates this value approximately every six hours. Recent changes might not be reflected in this value.

So the AWS DynamoDB has this limitation but emulation with `dynamodb-local` doesn't have it.

**Comment by prcongithub** [comment]
Thanks for the explanation. Closing this.
