### ISSUE TITLE
queries sometimes return a different model

### ISSUE THREAD

**Issue by rhuang** [Dynamoid/dynamoid#471]
Sometimes when I iterate through a query like `MyModel.where(...).each { ... }`, or when I find by the hash key like `MyModel.find`, the object that is returned would be from a different model. For example, `MyModel.find` would return `AnotherModel`. 

I can't reproduce this, but I see errors logged in the code daily that are like:

```
undefined method `some_method' for #<AnotherModel:0x000abcd>
```

I'm expecting `MyModel` but Dynamoid methods are returning `AnotherModel` for some reason. I've also put in logging to check returned instances, using `.is_a?` to validate. The code works as expected most of the time, but I'm seeing these type of errors come up more and more often, usually in the same place, and now with more and more models as the application is growing.

Wondering if you guys have any ideas as to what might be going on?

**Comment by andrykonchin** [comment]
The first idea that comes into my mind is STI. It would be explain such cases.

**Comment by rhuang** [comment]
`gem 'dynamoid', '3.3'`

Yes, some cases are STI:

```
class User; end;
class UserA < User; end;
class UserB < User; end;

UserB.where(...).each { ... } # returns `UserA` or the base `User` objects instead
```

I wasn't able to see any pattern to help me diagnose.

However, I also very recently seeing non-STI classes doing the same thing.

**Comment by andrykonchin** [comment]
It would be great it you provided any example to reproduce the issue. If there is a bug in Dynamoid it should be easily reproducible.

**Comment by rhuang** [comment]
I'm not exactly sure how to reproduce with code, but I can show you an example through my error logs and code if that can provide any help:

![image](https://user-images.githubusercontent.com/1022385/99141559-53578700-2601-11eb-9805-c2da12651201.png)
You can see here, that `GeocoderCache.find(...)` seems to return a `Lawyer` object, and both classes are totally unrelated. This is very strange.

Here are the snippets for both the `GeocoderCache` class and the `Lawyer` class:

```
class GeocoderCache
  include Dynamoid::Document
  table name: :geocoder_cache_tablename, key: some_key, capacity_demand: :on_demand
  ...
end

class Lawyer < User
...
end

class User
  include Dynamoid::Document
  table name: :some_users_table_name, key: :some_key, capacity_demand: :on_demand
  ...
end
```

This code path is run multiple times a day, but this error only happens sometimes, so I'm not sure how I can reproduce it.

This is in Rails 6.0, in `Zeitwerk` mode.

**Comment by andrykonchin** [comment]
It would be helpful to have examples of `GeocoderCache` items, for which this error is reproduced (and `find` returns instance of other class).

The only valid case as I mentioned above is STI. So we need to check whether these items have the `type` attribute in the DynamoDB table (or another attribute defined with `inheritance_field` option). It actually doesn't matter whether there is a declared field `type` in the model  - it's enough to have such attribute (`type`) stored in the DynamoDB table. As far as DynamoDB is schemaless and allows items to have own attributes it's quite possible that some items have additional not expected attributes.

If you confirm that these items don't have `type` attribute or have but values are correct (equal `"GeocoderCache"`) - then it's a Dynamoid bug. But without some particular example it would be difficult to figure out where the bug is.

**Comment by rhuang** [comment]
Thanks. I will see if I can capture the item body when this happens so that I can investigate if it has unexpected `type` fields. Hopefully this will help me determine if it's my code's fault with setting an unexpected `type` or if I am able to reproduce a bug.

**Comment by rhuang** [comment]
I did some logging of the type fields and I found an instance where it was my fault. I will close this for now, thanks!
