### ISSUE TITLE
Dynamic table names

### ISSUE THREAD

**Issue by filiptepper** [Dynamoid/Dynamoid#59]
I'm looking to split my data into time-sliced tables.

Before I do any work on this I wanted to ask I you would be interested in merging pull request that would allow dynamic tables names for a model (say, defined at runtime by a lambda).

**Comment by bglusman** [comment]
@filiptepper I'm curious what you'd propose here, but I also had need for dynamic table names for a different purpose, to segregate models containing PII on a per company basis.  I rolled some logic myself that dynamically generates a class inherting from the main class for each company, and the main class has no table name, and is thus an abstract or base class, only each concrete per-company version has a name, which is dynamically constructed, but they're also each unique concrete classes.  I think I could share the code if this would help you or others, though not sure if it suits your purposes as is, but happy to discuss/compare notes!

**Comment by cignoir** [comment]
@filiptepper I'm also interested in this proposal, because there is a use case that one model have two or more table names. For example, dividing a table into production and sandbox in spite of the same role. 

One solution is to make a inheritance relationship as below
(Maybe in the same way as @bglusman  did).
```
CarBase
├ CarProduction(table name: dynamoid_car_production)
└ CarSandbox(table name: dynamoid_car_sandbox)
```

However, it will be easier if there is a mechanism to determine the table names dynamically.

**Comment by filiptepper** [comment]
I was looking to work on this but we have simplified our data structure and it turns out we won't be using Dynamoid after all.

@cignoir For sandbox / production environment split I would rather use separate AWS accounts / credentials. I think that could simplify the code + extra security!
