### ISSUE TITLE
Config.namespace still adds namespacing even if set to nil

### ISSUE THREAD

**Issue by tvmendoza** [Dynamoid/Dynamoid#78]
I am setting my configuration to the following:

config.adapter = 'aws_sdk_v2' 
    config.namespace = nil
    config.warn_on_scan = true 
    config.read_capacity = 5
    config.write_capacity = 5 

However, when i get the result I am getting the following:

 get_item(table_name:"_tableName",key:{"email"=>{s:"a@a.com"}})  

In this example my table is called  "tableName" however it is still adding the _, I tried setting config.namespace to "" and nil but it did not work. 

Is this an error or did I just misunderstood the documentation?

**Comment by cignoir** [comment]
It seems to be working fine for me.
```ruby
require 'dynamoid'
require 'aws-sdk'

Dynamoid.configure do |config|
  config.adapter = 'aws_sdk_v2'
  config.namespace = nil
  config.endpoint = 'http://localhost:8000'
end

class SampleModel
  include Dynamoid::Document
  table name: 'table_name'
end

p SampleModel.table_name
#=> "table_name"

SampleModel.create_table
p Dynamoid::adapter.list_tables
#=> ["table_name"]
```


And also all specs passed on my local.
```
$ bundle exec rspec spec

...

Finished in 3 minutes 26.9 seconds (files took 0.66104 seconds to load)
309 examples, 0 failures, 4 pending
```

**Comment by alexperto** [comment]
same problem here!

```
class Measurement
  include Dynamoid::Document

  table name: 'api_data'
end
```

```
2.3.0 :003 > Measurement.table_name
 => "_api_data"
```

what version are you using @cignoir?

**Comment by alexperto** [comment]
it seems like the code is fine, for some reason the latest version didn't work for me, when I used a forked repo it worked perfectly. Anyways, I created a PR to refactor the table-namespacing stuff 

https://github.com/Dynamoid/Dynamoid/pull/79/files

**Comment by cignoir** [comment]
@alexperto 
I tested with v1.1.0. But I directly cloned the latest source codes via github (not rubygems).

I think this causes problems. The namespacing problem was fixed on Mar 12, 2016. However, the version on rubygems not updated since December 30, 2015. 

@philipmw 
Is it time to bump up version and push gem?

**Comment by alexperto** [comment]
thanks for looking at it @cignoir,
I temporary fixed it by doing:

```
gem "dynamoid", git: "https://github.com/Dynamoid/Dynamoid.git"
```

**Comment by bglusman** [comment]
If anyone else needs a gem based distribution, we're working on a new one but I had related issue and created dynamoid-edge gem release of a current master snapshot a few months back that will probably fix your issue @tvmendoza , but hopefully @pboling or I will be able to get a new gem release out on the official gem soon.

**Comment by archonic** [comment]
Master branch indeed fixes it, but I'm hoping the release with that fix is pushed to rubygems before we're ready to release our feature. Don't want to be bundling an unversioned branch in production!

**Comment by pboling** [comment]
@bglusman @archonic I am going to release a patch update from current master, to get this particular fix out.  We have a lot of other work to do that will need to be in bigger releases.

**Comment by pboling** [comment]
# 1.2.0

* Expose and fix truncate method on adapter (#52, @pcorpet)
* Enable saving without updating timestamps (#58, @cignoir)
* Fix projected attributes by checking for :include (#56, @yoshida_tetsuhiro)
* Make behavior of association where method closer to AR by cloning instead of modifying (#51, @pcorpet)
* Add boolean field presence validator (#50, @pcorpet)
* Add association build method (#49, @pcorpet)
* Fix association create method (#47, #48, @pcorpet)
* Support range_between (#42, @ayemos)
* Fix problems with range query (#42, @ayemos)
* Don't prefix table names when namespace is nil (#40, @brenden)
* Added basic secondary index support (#34, @sumocoder)
* Fix query attribute behavior for booleans (#35, @amirmanji)
* Ignore unknown fields on model initialize (PR #33, @sumocoder)

**Comment by pboling** [comment]
Been trying to no avail to get specs passing.  Also made a few other improvements.  1.2.0 coming tomorrow I expect.
https://github.com/Dynamoid/Dynamoid/pull/100  Please review and comment!

**Comment by pboling** [comment]
Release 1.2.0.  Please check it out!
